//addEventListener for two buttons and function 
document.querySelector('#bet10').addEventListener('click', bet10)
document.querySelector('#bet20').addEventListener('click', bet20)

//Assing an initial point value to total amount -> 
//Assigned as let variable (constant updates)
let total= 100

//Assigning variable to image placeholders in HTML
let img1 = document.querySelector('#img1')
let img2 = document.querySelector('#img2')
let img3 = document.querySelector('#img3')

//Array of images to replace placeholder in HTML 
let thanksJoyce = [
    '<img src="img/astro2.webp"></img>',
    '<img src="img/astro3.avif"></img>',
    '<img src="img/astro4.webp"></img>',
    '<img src="img/astro5.avif"></img>',
    '<img src="img/astro6.avif"></img>'
]


function bet10(){
    //box/slot assigned to thanksJoyce array. 
    //img seleceted by a random number generated by Math.random
    const box1 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)] ;
    const box2 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)] ;
    const box3 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)] ;

    //Replace placeholder image with random image
    //.innerHTML was required to run the images (vs.innerText)
    img1.innerHTML = box1
    img2.innerHTML = box2
    img3.innerHTML = box3

    //conditional for message
    if(total < 10 || total===0){
        bet10.disable = true
    }else if(box1===box2 && box1===box3){
        document.querySelector('#placeToSee').innerText = "You win"
        total = total + 10 * 10
        document.querySelector('#balance').innerText = total
    }else {
        document.querySelector('#placeToSee').innerText = "You Lose"
        total= total - 10
        document.querySelector('#balance').innerText= total
    } 
    
}

function bet20(){
    const box1 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)];
    const box2 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)];
    const box3 = thanksJoyce[Math.floor(Math.random() * thanksJoyce.length)];
    img1.innerHTML = box1
    img2.innerHTML = box2
    img3.innerHTML = box3
    //conditionals for winner message
    //disable button when money runs out
    if(total < 20 || total===0){
        bet20.disable = true

    } else if(box1===box2 && box1===box3){
        document.querySelector('#placeToSee').innerText = "You win"
        total = total + 20 * 10
        document.querySelector('#balance').innerText = total

    } else {
        document.querySelector('#placeToSee').innerText = "You Lose"
        total = total- 20
        document.querySelector('#balance').innerText= total

    }
      if(box1===box2 && box1===box3){
        document.querySelector('#placeToSee').innerText = "You win"
    }else {
        document.querySelector('#placeToSee').innerText = "You Lose"
    }
    
   
}
